version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    env_file:
      - devcontainer.env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=demo
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  recipe:
    container_name: crud_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - devcontainer.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/demo
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db

volumes:
  db-data: